apiVersion: v1
kind: Namespace
metadata: 
  name: webapp-development
---
kind: Service
apiVersion: v1
metadata:
  name: webapp-development
  namespace: webapp-development
spec:
  selector:
    app: webapp-development
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-development-deployment
  namespace: webapp-development
  labels:
    app: webapp-development
spec:
  replicas: 6
  selector:
    matchLabels:
      app: webapp-development
  template:
    metadata:
      labels:
        app: webapp-development
    spec:
      containers:
      - name: webapp-development
        image: alexanderh12/circleci:$TAG
        ports:
        - containerPort: 80
